Repository pythonitalia/python-italy-telegram-bot, pull requests merged in 2019-07, with the labels that each got.

#1 Supporto a docker, aggiunta docs, refactoring
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  config.sample
  docker/dev/Dockerfile
  docker/dev/Pipfile
  docker/dev/Pipfile.lock
  docker/dev/docker-compose.yml
  tg_bot/__init__.py
  tg_bot/modules/spam.py
Labels: documentation, enhancement

#13 Traduzione modulo log_channel
  tg_bot/modules/log_channel.py
Labels: translation

#14 Traduzione modulo sed
  tg_bot/modules/sed.py
Labels: translation

#15 Traduzione modulo users
  tg_bot/modules/users.py
Labels: translation

#12 Update README.md
  README.md
Labels: documentation

#17 FIX ISSUE #16 BUG
  tg_bot/__init__.py
  tg_bot/modules/log_channel.py
  tg_bot/modules/spam.py
Labels: resolved

#18 Traduzione modulo locks
  tg_bot/modules/locks.py
Labels: translation
